Api endpoints
ahmetbozaci/ror-social-scaffold pull request #10
Opened 2022-01-17 13:39 UTC by ahmetbozaci

API endpoints :

- list all posts.
- list all comments for a post.
- add a comment to a post
- Add authentication to your API endpoints.

2022-01-17 17:31 UTC, Emmyn5600 requested changes
Hi @ahmetbozaci  @emmanuellekamwa  and @CollinsTatang 

Great work on making the project requirements 👏 
You've done well implementing some of the project requirements, but there are still some which aren't addressed yet, please work on it and ask for another review.

 ## Required Changes ♻️

- Kindly, include the endpoints you have implemented in the readme file.

## Optional suggestions

- n/a

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-01-17 17:31 UTC, Emmyn5600 commented on app/auth/authenticate_user.rb
> +end
- [ ] Endpoint of the login or authentication doesn't work as expected. Please fix it.

![api4](https://user-images.githubusercontent.com/55635977/149813707-6d5b8e65-486a-46fd-8cc1-c169c9fbd9af.png)

2022-01-17 17:31 UTC, Emmyn5600 commented on app/controllers/authentication_controller.rb
> +end
- [ ] Kindly, return the response in the JSON format after sending a request.

![api3](https://user-images.githubusercontent.com/55635977/149814040-1330a9dd-6b06-48c3-8e47-9c9bc87a2630.png)

2022-01-20 10:46 UTC, AshakaE approved these changes
### Hi @ahmetbozaci   🙋‍♀️, 

# STATUS APPROVED ✔
   
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 10:24 UTC, merged