Review request - Social media web app
ahmetbozaci/ror-social-scaffold pull request #3
Opened 2021-03-18 17:49 UTC by ahmetbozaci

**Milestone 2 - Friendship v1**

- Create model association for friendship
- Implement user profile to show
- Pending Friends
- Friends
- Show all user

2021-03-18 19:43 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @ahmetbozaci & @chrystalme**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] please make sure to add unit and integration tests as you didn't add any.
- [x] users can only see posts that are created by them or users who are friends. right now a user can see a post created by a non-friend user.
- [x] when I click on invite to friendship I can't see the invite anywhere. not in the users#index page nor in the user#show page.
- [x] when I click on invite to friends, the friendship status should be converted to pending and the button should be removed. if the friendship is accepted you should display "friend" next to the user's name. if not, you should add the button again. 


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-03-25 16:51 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hello @ahmetbozaci and @chrystalme, Great job! 👏  Both of you have done well on this project.

> Great codebase 👍 

However, there are still some changes that are necessary for this project to be approved.
Let us quickly add some finishing touches and request another review.

- [ ] Your posts timeline should include posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)), Currently I can see post from users that are not logged-in user friend.

- [ ] There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright)
I have gone ahead and made some comments on your codebase see affected files below:

**Don't know where to start or how to?** See  [Rails View Helpers Best Practices](https://medium.com/@acushla4real/rails-view-helpers-best-practices-guide-d7d7b6db3db4) 

- [ ] I see you have nicely implemented unit tests on all your model, kindly add integration tests as well.  [Capybara](https://github.com/teamcapybara/capybara) is an exceptionally great tool for performing an integration test with RSpec because it helps you perform end-to-end tests on your applications. It does this by simulating how a real user would interact with your application. Want to know more? See this [article](https://www.microverse.org/blog/understanding-rspec-controller-request-specs-integration-test-using-capybara). 
- [ ] Don't forget to take care of all your pending tests.

- [ ] Your ReadMe file still carries the app template description. "This repo includes initial code for social media app with basic styling. Its purpose is to be a starting point for Microverse students." I am sure you will agree with me, this repo no longer carries initial code, you have done a lot. Do well to update it to reflect what the app is all about. Possibly a screenshot too, to give it that professional look.


### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2021-03-25 16:51 UTC, acushlakoncept commented on app/helpers/application_helper.rb
> +  # end
It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
See this [post](https://stackoverflow.com/questions/13130859/inline-comments-in-ruby/13130900#:~:text=No%2C%20Ruby%20does%20not%20have,comment%20out%20the%20one%20row), about why comments are discouraged.

2021-03-25 16:51 UTC, acushlakoncept commented on app/models/user.rb
> +  # Users who have requested to be friends
It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
See this [post](https://stackoverflow.com/questions/13130859/inline-comments-in-ruby/13130900#:~:text=No%2C%20Ruby%20does%20not%20have,comment%20out%20the%20one%20row), about why comments are discouraged.

2021-03-25 16:51 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
> +    <%#= link_to gravatar_image_tag(current_user.email, gravatar: { :size => 15 }, alt: current_user.name) %>
It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
See this [post](https://stackoverflow.com/questions/13130859/inline-comments-in-ruby/13130900#:~:text=No%2C%20Ruby%20does%20not%20have,comment%20out%20the%20one%20row), about why comments are discouraged.

2021-03-25 16:51 UTC, acushlakoncept commented on app/views/layouts/application.html.erb
> +  </div>
There should be absolutely NO logic in views.

2021-03-25 16:51 UTC, acushlakoncept commented on app/views/users/show.html.erb
> +  <% current_user.pending_friendships.each do |pf| %>
There should be absolutely NO logic in views.

2021-03-25 16:51 UTC, acushlakoncept commented on app/views/users/profile.html.erb
> +<% end %>
There should be absolutely NO logic in views.

2021-03-25 16:51 UTC, acushlakoncept commented on app/views/users/_user.html.erb
> +  <% end %>
There should be absolutely NO logic in views.

2021-03-27 00:22 UTC, BrianSammit approved these changes
STATUS: APPROVED :green_circle: :1st_place_medal: 
-------------
Hello, @ahmetbozaci @chrystalme You did an excellent job on this milestone. Good job working on the required changes :muscle: I really like how the project looks. :1st_place_medal: :100: .
---------------
You can merge this milestone now :smile: 
Reach me on SLACK if you have any question 
@ Brian Sammit Cruz Rodriguez 
HAPPY CODING!! AND GOOD LUCK WITH THR NEXT MILESTONES. :crossed_fingers: :four_leaf_clover: 

![Well-Done-Applause](https://user-images.githubusercontent.com/64173189/112704412-80962a80-8e68-11eb-8364-21357329ef27.gif)

2021-03-27 23:45 UTC, merged